//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADSLNumberConfiguration
    {
        public int ADSLNumberConfigurationID { get; set; }
        public string Prefix { get; set; }
        public int LineMinimumLength { get; set; }
        public int LineMaximumLength { get; set; }
        public string ProvinceName { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
    }
}
