//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentLimitCycle
    {
        public int AgentLimitCycleID { get; set; }
        public int AgentLimitGroupID { get; set; }
        public int LimitCycleID { get; set; }
        public string Time { get; set; }
        public string Day { get; set; }
        public Nullable<int> Date { get; set; }
        public string Month { get; set; }
    
        public virtual AgentLimitGroup AgentLimitGroup { get; set; }
        public virtual LimitCycle LimitCycle { get; set; }
    }
}
