//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertNotificationUser
    {
        public int AlertNotificationUserID { get; set; }
        public int AlertNotificationID { get; set; }
        public int UserID { get; set; }
        public string Method { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
    
        public virtual AlertNotification AlertNotification { get; set; }
        public virtual User User { get; set; }
    }
}
