//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMenuGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppMenuGroup()
        {
            this.AppMenus = new HashSet<AppMenu>();
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int AppMenuGroupID { get; set; }
        public string Name { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public bool IsActive { get; set; }
        public int ConfigVersion { get; set; }
        public int ServiceConfig { get; set; }
        public string WelcomeMessage { get; set; }
        public string HomeScreenTitle { get; set; }
        public string MarketingMessage { get; set; }
        public string Logo { get; set; }
        public Nullable<int> AppReleaseID { get; set; }
        public Nullable<int> HeartbeatInterval { get; set; }
        public Nullable<int> LocationPollInterval { get; set; }
        public string EnforceUpdate { get; set; }
        public string MarketingMessage2 { get; set; }
        public string MarketingMessage3 { get; set; }
        public Nullable<System.DateTime> MandatoryBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppMenu> AppMenus { get; set; }
        public virtual AppRelease AppRelease { get; set; }
        public virtual Institution Institution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
