//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserSetting
    {
        public int AppUserSettingID { get; set; }
        public int AppSettingParameterID { get; set; }
        public int AppSettingValueID { get; set; }
        public int UserID { get; set; }
    
        public virtual AppSettingParameter AppSettingParameter { get; set; }
        public virtual AppSettingValue AppSettingValue { get; set; }
        public virtual User User { get; set; }
    }
}
