//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        public string Controller { get; set; }
        public string Method { get; set; }
        public string Description { get; set; }
        public string OperationType { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int UserID { get; set; }
        public int InstitutionID { get; set; }
        public Nullable<int> SubModuleID { get; set; }
        public string SubModule { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public string Machine { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual User User { get; set; }
    }
}
