//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryField
    {
        public int BeneficiaryFieldID { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public bool IsActive { get; set; }
        public string DisplayName { get; set; }
        public string PlaceHolderText { get; set; }
        public bool IsMandatory { get; set; }
        public int CorridorCurrencyID { get; set; }
        public int Sequence { get; set; }
        public string FieldOptions { get; set; }
        public int ScreenNumber { get; set; }
        public string KeyboardType { get; set; }
        public bool IsSecureText { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
    
        public virtual CorridorCurrency CorridorCurrency { get; set; }
    }
}
