//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillerCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillerCatalog()
        {
            this.SKUCatalogs = new HashSet<SKUCatalog>();
        }
    
        public int PdBillerID { get; set; }
        public bool IsActive { get; set; }
        public string Host { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string UpdatedBy { get; set; }
        public string ImageName { get; set; }
        public string DisplayName { get; set; }
        public string CatalogVersion { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string BillerID { get; set; }
        public string BillerName { get; set; }
        public string BillerType { get; set; }
        public string BillerDescription { get; set; }
        public string PdTransactionCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUCatalog> SKUCatalogs { get; set; }
    }
}
