//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCollection
    {
        public int CashCollectionID { get; set; }
        public int AgentSettlementCycleID { get; set; }
        public int UserID { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string RecvRefID { get; set; }
        public Nullable<double> CashInHand { get; set; }
        public Nullable<double> NewCashInHand { get; set; }
    
        public virtual AgentSettlementCycle AgentSettlementCycle { get; set; }
        public virtual User User { get; set; }
    }
}
