//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeLog
    {
        public int ChequeLogID { get; set; }
        public int TransactionLogID { get; set; }
        public int UserID { get; set; }
        public System.DateTime ProcessingDateTime { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual TransactionLog TransactionLog { get; set; }
        public virtual User User { get; set; }
    }
}
