//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionTransactionMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommissionTransactionMethod()
        {
            this.CommissionRates = new HashSet<CommissionRate>();
        }
    
        public int CommissionTransactionMethodID { get; set; }
        public int CommissionGroupID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public int HostTransactionCodeID { get; set; }
        public string Type { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual CommissionGroup CommissionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionRate> CommissionRates { get; set; }
        public virtual HostTransactionCode HostTransactionCode { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
