//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionRate
    {
        public int CommissionRateID { get; set; }
        public int CommissionTransactionMethodID { get; set; }
        public double RangeFrom { get; set; }
        public double RangeTo { get; set; }
        public double Fee { get; set; }
        public string Type { get; set; }
    
        public virtual CommissionTransactionMethod CommissionTransactionMethod { get; set; }
    }
}
