//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateVerificationOption
    {
        public int CorporateVerficationOptionID { get; set; }
        public int CorporateID { get; set; }
        public int VerficationOptionID { get; set; }
    
        public virtual Corporate Corporate { get; set; }
        public virtual VerificationOption VerificationOption { get; set; }
    }
}
