//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorridorCurrency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CorridorCurrency()
        {
            this.BeneficiaryFields = new HashSet<BeneficiaryField>();
        }
    
        public int CorridorCurrencyID { get; set; }
        public int CorridorID { get; set; }
        public int CurrencyID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> RemittanceTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryField> BeneficiaryFields { get; set; }
        public virtual Corridor Corridor { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual RemittanceType RemittanceType { get; set; }
    }
}
