//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryBank
    {
        public int CountryBankID { get; set; }
        public int CountryID { get; set; }
        public int BankID { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Country Country { get; set; }
    }
}
