//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReviewItem
    {
        public int CustomerReviewItemID { get; set; }
        public string Type { get; set; }
        public string Issue { get; set; }
        public string Discription { get; set; }
        public int CustomerReviewID { get; set; }
    
        public virtual CustomerReview CustomerReview { get; set; }
    }
}
