//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocument
    {
        public int CustomerDocumentID { get; set; }
        public int CustomerID { get; set; }
        public string Type { get; set; }
        public string FileName { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Image { get; set; }
        public string IDNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
