//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.AgentSearchHistories = new HashSet<AgentSearchHistory>();
            this.CustomerQuestionnaires = new HashSet<CustomerQuestionnaire>();
            this.LocationSearchHistories = new HashSet<LocationSearchHistory>();
            this.CustomerFeedbacks = new HashSet<CustomerFeedback>();
            this.CustomerAccounts = new HashSet<CustomerAccount>();
            this.CustomerActivities = new HashSet<CustomerActivity>();
            this.CustomerBeneficiaries = new HashSet<CustomerBeneficiary>();
            this.CustomerDocuments = new HashSet<CustomerDocument>();
            this.CustomerKins = new HashSet<CustomerKin>();
            this.CustomerOTPs = new HashSet<CustomerOTP>();
            this.CustomerReviews = new HashSet<CustomerReview>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string NationalID { get; set; }
        public string PassportNumber { get; set; }
        public string Contact { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public bool IsActive { get; set; }
        public int InstitutionID { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> LastAccountLocked { get; set; }
        public string AccountStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TagID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CurrencyCode { get; set; }
        public string City { get; set; }
        public string Occupation { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string PostalCode { get; set; }
        public string BankID { get; set; }
        public string BusinessName { get; set; }
        public string DeviceID { get; set; }
        public string DeviceToken { get; set; }
        public string DeviceType { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentSearchHistory> AgentSearchHistories { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerQuestionnaire> CustomerQuestionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationSearchHistory> LocationSearchHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAccount> CustomerAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerActivity> CustomerActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBeneficiary> CustomerBeneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDocument> CustomerDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerKin> CustomerKins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOTP> CustomerOTPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerReview> CustomerReviews { get; set; }
    }
}
