//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWallet
    {
        public int CustomerWalletID { get; set; }
        public int CustomerID { get; set; }
        public string WalletType { get; set; }
        public string WalletNumber { get; set; }
        public string CurrencyCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
    }
}
