//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBeneficiary
    {
        public int CustomerBeneficiaryID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string NationalID { get; set; }
        public string PassportNumber { get; set; }
        public string Contact { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime Created { get; set; }
        public string BankCode { get; set; }
        public string BankAccountNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> RemittanceTypeID { get; set; }
        public bool IsActive { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> AvatarID { get; set; }
        public string Picture { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual RemittanceType RemittanceType { get; set; }
        public virtual State State { get; set; }
    }
}
