//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceAlertStatus = new HashSet<DeviceAlertStatu>();
            this.DeviceSets = new HashSet<DeviceSet>();
            this.TerminalDevices = new HashSet<TerminalDevice>();
        }
    
        public int DeviceID { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public int TerminalTypeID { get; set; }
        public bool IsCritical { get; set; }
        public bool IsActive { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsSupply { get; set; }
        public Nullable<bool> IsHealth { get; set; }
    
        public virtual TerminalType TerminalType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceAlertStatu> DeviceAlertStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceSet> DeviceSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalDevice> TerminalDevices { get; set; }
    }
}
