//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSet
    {
        public int DeviceSetID { get; set; }
        public int DeviceTypeID { get; set; }
        public int DeviceID { get; set; }
        public bool IsCritical { get; set; }
        public int SupplyThreshold { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
