//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRemark
    {
        public int DeviceRemarkID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TerminalDeviceEventID { get; set; }
    
        public virtual TerminalDeviceEvent TerminalDeviceEvent { get; set; }
        public virtual User User { get; set; }
    }
}
