//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisputedTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisputedTransaction()
        {
            this.DisputedTransactionRemarks = new HashSet<DisputedTransactionRemark>();
            this.RepostDetails = new HashSet<RepostDetail>();
        }
    
        public int DisputedTransactionID { get; set; }
        public int TerminalID { get; set; }
        public string SourceTransactionID { get; set; }
        public System.DateTime SourceDateTime { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string TransactionDetail { get; set; }
        public string TransactionType { get; set; }
        public string ConsumerID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Reason { get; set; }
        public int TerminalTypeID { get; set; }
        public Nullable<int> TransactionLogID { get; set; }
        public string Status { get; set; }
        public string Request { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisputedTransactionRemark> DisputedTransactionRemarks { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepostDetail> RepostDetails { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual TerminalType TerminalType { get; set; }
        public virtual TransactionLog TransactionLog { get; set; }
    }
}
