//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class DProduct
    {
        public string SkuCode { get; set; }
        public string LocalizationKey { get; set; }
        public string SettingDefinitions { get; set; }
        public double CommissionRate { get; set; }
        public string ProcessingMode { get; set; }
        public string RedemptionMechanism { get; set; }
        public string Benefits { get; set; }
        public string ProductType { get; set; }
        public string ValidityPeriodIso { get; set; }
        public string UatNumber { get; set; }
        public string AdditionalInformation { get; set; }
        public string DefaultDisplayText { get; set; }
        public string RegionCode { get; set; }
        public double CustomerFee { get; set; }
        public double DistributorFee { get; set; }
        public double ReceiveValue { get; set; }
        public string ReceiveCurrencyIso { get; set; }
        public double ReceiveValueExcludingTax { get; set; }
        public double TaxRate { get; set; }
        public string TaxName { get; set; }
        public string TaxCalculation { get; set; }
        public double SendValue { get; set; }
        public string SendCurrencyIso { get; set; }
        public double ProductValue { get; set; }
        public int ProductID { get; set; }
        public string ProviderCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DProvider DProvider { get; set; }
        public virtual DRegion DRegion { get; set; }
    }
}
