//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class DProviderRegion
    {
        public int ID { get; set; }
        public string ProviderCode { get; set; }
        public string RegionCode { get; set; }
    
        public virtual DProvider DProvider { get; set; }
        public virtual DRegion DRegion { get; set; }
    }
}
