//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.DriverVehicleGroups = new HashSet<DriverVehicleGroup>();
            this.DriverVerificationOptions = new HashSet<DriverVerificationOption>();
        }
    
        public int DriverID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public int CorporateID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> DailyLimit { get; set; }
        public Nullable<int> MonthlyLimit { get; set; }
        public string NFCTag { get; set; }
        public string Passport { get; set; }
        public string NationalID { get; set; }
        public string DrivingLicense { get; set; }
        public string Picture { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Corporate Corporate { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverVehicleGroup> DriverVehicleGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverVerificationOption> DriverVerificationOptions { get; set; }
    }
}
