//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverVehicleGroup
    {
        public int DriverVehicleGroup1 { get; set; }
        public int VehicleGroupID { get; set; }
        public int DriverID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual VehicleGroup VehicleGroup { get; set; }
    }
}
