//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public int ExchangeRateID { get; set; }
        public int CurrencyFromID { get; set; }
        public int CurrencyToID { get; set; }
        public Nullable<double> Buy { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public bool IsActive { get; set; }
        public Nullable<double> Sell { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
