//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeRate
    {
        public int FeeRateID { get; set; }
        public Nullable<double> RangeFrom { get; set; }
        public Nullable<double> RangeTo { get; set; }
        public double Fee { get; set; }
        public int CurrencyID { get; set; }
        public int FeeGroupID { get; set; }
        public string Type { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual FeeGroup FeeGroup { get; set; }
    }
}
