//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralLedger
    {
        public int GeneralLedgerID { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public int GeneralLedgerHeadID { get; set; }
        public int TransactionLogID { get; set; }
    
        public virtual GeneralLedgerHead GeneralLedgerHead { get; set; }
        public virtual TransactionLog TransactionLog { get; set; }
    }
}
