//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Host()
        {
            this.HostEvents = new HashSet<HostEvent>();
            this.HostResponseCodes = new HashSet<HostResponseCode>();
            this.HostSettlementCycles = new HashSet<HostSettlementCycle>();
            this.HostTransactionCodes = new HashSet<HostTransactionCode>();
            this.MessageMappings = new HashSet<MessageMapping>();
        }
    
        public int HostID { get; set; }
        public string Name { get; set; }
        public int CountryID { get; set; }
        public string Code { get; set; }
        public int InstitutionID { get; set; }
        public string Protocol { get; set; }
        public System.DateTime Created { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string SettlementCycle { get; set; }
        public string Time { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string SettlementType { get; set; }
        public string Day { get; set; }
        public Nullable<int> Date { get; set; }
        public int Timeout { get; set; }
        public int NoOfFailTxn { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Institution Institution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostEvent> HostEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostResponseCode> HostResponseCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostSettlementCycle> HostSettlementCycles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostTransactionCode> HostTransactionCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageMapping> MessageMappings { get; set; }
    }
}
