//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryLog
    {
        public int InventoryLogID { get; set; }
        public int StoreID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime ProcessingDate { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> FromStoreID { get; set; }
        public System.DateTime Created { get; set; }
        public string Type { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
    }
}
