//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventorySaleItem
    {
        public int InventorySaleItemID { get; set; }
        public int InventorySaleID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public double PricePerItem { get; set; }
        public double ItemTotal { get; set; }
    
        public virtual InventorySale InventorySale { get; set; }
        public virtual Product Product { get; set; }
    }
}
