//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class IOCatalog
    {
        public int PdIOID { get; set; }
        public int PdSKUID { get; set; }
        public bool IsActive { get; set; }
        public string CatalogVersion { get; set; }
        public string BillerID { get; set; }
        public string SKU { get; set; }
        public int IOID { get; set; }
        public int Type { get; set; }
        public int Operation { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Datatype { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
        public string ValidLengths { get; set; }
    
        public virtual SKUCatalog SKUCatalog { get; set; }
    }
}
