//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public Nullable<int> MinimumQuantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> InstitutionID { get; set; }
    
        public virtual Institution Institution { get; set; }
    }
}
