//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int JournalID { get; set; }
        public int JournalCategoryID { get; set; }
        public string STAN { get; set; }
        public int TerminalID { get; set; }
        public string Description { get; set; }
        public System.DateTime JournalDateTime { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual JournalCategory JournalCategory { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
