//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMapping
    {
        public int MessageMappingID { get; set; }
        public string Direction { get; set; }
        public string Field { get; set; }
        public int Length { get; set; }
        public string MapTag { get; set; }
        public int HostID { get; set; }
    
        public virtual Host Host { get; set; }
    }
}
