//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleAttribute
    {
        public int ModuleAttributeID { get; set; }
        public int ModuleID { get; set; }
        public int AttributeID { get; set; }
        public int PermissionGroupID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Module Module { get; set; }
        public virtual PermissionGroup PermissionGroup { get; set; }
    }
}
