//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewLine
    {
        public int NewLineID { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string DisplayNameEnglish { get; set; }
        public string DisplayNameArabic { get; set; }
        public string DescriptionEnglish { get; set; }
        public string DescriptionArabic { get; set; }
        public double Price { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
        public int Sequence { get; set; }
    }
}
