//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDelivery
    {
        public int NotificationDeliveryID { get; set; }
        public int NotificationID { get; set; }
        public int UserGroupID { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
