//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferAttribute
    {
        public int OfferAttrID { get; set; }
        public Nullable<bool> AttrUsed { get; set; }
        public string AttrPName { get; set; }
        public string AttrPValue { get; set; }
        public Nullable<int> AttrType { get; set; }
        public string AttrArabicName { get; set; }
        public string AttrEnglishName { get; set; }
        public Nullable<bool> AttrMandatory { get; set; }
        public Nullable<int> OfferID { get; set; }
    
        public virtual Offer Offer { get; set; }
    }
}
