//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferStore
    {
        public int OfferStoreId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual InstitutionStore InstitutionStore { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
