//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineHelp
    {
        public int OnlineHelpID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int SequenceNumber { get; set; }
        public int OnlineHelpGroupID { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual OnlineHelpGroup OnlineHelpGroup { get; set; }
    }
}
