//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordPolicy
    {
        public int PasswordPolicyID { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; set; }
        public bool IsAlphaNumeric { get; set; }
        public int PasswordValidity { get; set; }
        public int PasswordHistory { get; set; }
        public int InvalidAttemptsAllowed { get; set; }
        public int LockoutInterval { get; set; }
        public int SessionTimeout { get; set; }
        public int MinUpperCase { get; set; }
        public int MinSpecialCharacter { get; set; }
        public bool IsClearText { get; set; }
        public bool IsCaptcha { get; set; }
        public bool IsActive { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Institution Institution { get; set; }
    }
}
