//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCycle
    {
        public int PaymentCycleID { get; set; }
        public int AgentLimitGroupID { get; set; }
        public int LimitCycleID { get; set; }
        public int PaymentLimitID { get; set; }
        public bool IsSameAsParent { get; set; }
        public Nullable<double> Amount { get; set; }
        public bool IsActive { get; set; }
        public bool IsOffline { get; set; }
    
        public virtual AgentLimitGroup AgentLimitGroup { get; set; }
        public virtual LimitCycle LimitCycle { get; set; }
        public virtual PaymentLimit PaymentLimit { get; set; }
    }
}
