//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceCycle
    {
        public int PerformanceCycleID { get; set; }
        public int PerformanceGroupID { get; set; }
        public int LimitCycleID { get; set; }
        public int HostTransactionCodeID { get; set; }
        public bool IsPartOfParent { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<int> Volume { get; set; }
        public bool IsActive { get; set; }
    
        public virtual HostTransactionCode HostTransactionCode { get; set; }
        public virtual LimitCycle LimitCycle { get; set; }
        public virtual PerformanceGroup PerformanceGroup { get; set; }
    }
}
