//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidAmount
    {
        public int PrepaidAmountID { get; set; }
        public int Amount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Status { get; set; }
        public int Sequence { get; set; }
        public int RefillID { get; set; }
        public int PrepaidTypeID { get; set; }
        public int TerminalTypeID { get; set; }
    }
}
