//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskConfiguration
    {
        public int RiskConfigurationID { get; set; }
        public string RiskControl { get; set; }
        public string ControlLevel { get; set; }
        public string Protocol { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string MappingFile { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Institution Institution { get; set; }
    }
}
