//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rollout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rollout()
        {
            this.Terminals = new HashSet<Terminal>();
        }
    
        public int RolloutID { get; set; }
        public string KioskGroups { get; set; }
        public string Kiosks { get; set; }
        public System.DateTime Created { get; set; }
        public int AppReleaseID { get; set; }
        public string EnforceUpdate { get; set; }
        public Nullable<System.DateTime> MandatoryBy { get; set; }
    
        public virtual AppRelease AppRelease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terminal> Terminals { get; set; }
    }
}
