//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTemplate
    {
        public int ServiceTemplateID { get; set; }
        public int ServiceID { get; set; }
        public int TemplateID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Template Template { get; set; }
    }
}
