//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SKUCatalog()
        {
            this.IOCatalogs = new HashSet<IOCatalog>();
        }
    
        public int PdSKUID { get; set; }
        public int PdBillerID { get; set; }
        public bool IsActive { get; set; }
        public string DefaultDisplayText { get; set; }
        public double PaymentAmount { get; set; }
        public double Commission { get; set; }
        public string CommissionType { get; set; }
        public string CatalogVersion { get; set; }
        public string BillerID { get; set; }
        public string SKU { get; set; }
        public string Currency { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public bool InquiryAvailable { get; set; }
        public bool PartialPaymentAllowed { get; set; }
        public bool ExcessPaymentAllowed { get; set; }
        public bool PastDuePaymentAllowed { get; set; }
        public double Amount { get; set; }
        public Nullable<double> MinAmount { get; set; }
        public Nullable<double> MaxAmount { get; set; }
        public int DaysToPost { get; set; }
        public bool BusinessDays { get; set; }
    
        public virtual BillerCatalog BillerCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IOCatalog> IOCatalogs { get; set; }
    }
}
