//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        public int SMSID { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public int RetryCount { get; set; }
        public string DesRefID { get; set; }
        public string ContactNumber { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMSG { get; set; }
    }
}
