//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateTransactionField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateTransactionField()
        {
            this.TemplateScreenFields = new HashSet<TemplateScreenField>();
            this.TemplateTransactionFieldOpts = new HashSet<TemplateTransactionFieldOpt>();
            this.TempTransactionPlaceholders = new HashSet<TempTransactionPlaceholder>();
        }
    
        public int TemplateTransactionFieldID { get; set; }
        public int TemplateID { get; set; }
        public int TransactionFieldID { get; set; }
    
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateScreenField> TemplateScreenFields { get; set; }
        public virtual TransactionField TransactionField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateTransactionFieldOpt> TemplateTransactionFieldOpts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempTransactionPlaceholder> TempTransactionPlaceholders { get; set; }
    }
}
