//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateScreenField
    {
        public int TemplateScreenFieldID { get; set; }
        public int TemplateScreenID { get; set; }
        public int TemplateTransactionFieldID { get; set; }
        public Nullable<int> DisplaySequence { get; set; }
    
        public virtual TemplateScreen TemplateScreen { get; set; }
        public virtual TemplateTransactionField TemplateTransactionField { get; set; }
    }
}
