//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateScreen()
        {
            this.TemplateScreenFields = new HashSet<TemplateScreenField>();
        }
    
        public int TemplateScreenID { get; set; }
        public int TemplateID { get; set; }
        public int ScreenID { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Screen Screen { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateScreenField> TemplateScreenFields { get; set; }
    }
}
