//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTransactionPlaceholder
    {
        public int TempTransactionPlaceholderID { get; set; }
        public int TemplateTransactionFieldID { get; set; }
        public int TransactionPlaceholderID { get; set; }
    
        public virtual TemplateTransactionField TemplateTransactionField { get; set; }
        public virtual TransactionPlaceholder TransactionPlaceholder { get; set; }
    }
}
