//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalGroupConfig
    {
        public int ConfigID { get; set; }
        public int TerminalGroupID { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigValue { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual TerminalGroup TerminalGroup { get; set; }
    }
}
