//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terminal()
        {
            this.AlertNotifications = new HashSet<AlertNotification>();
            this.DisputedTransactions = new HashSet<DisputedTransaction>();
            this.ForceRestarts = new HashSet<ForceRestart>();
            this.Journals = new HashSet<Journal>();
            this.KioskLogs = new HashSet<KioskLog>();
            this.TerminalAppVersions = new HashSet<TerminalAppVersion>();
            this.TerminalCashCollections = new HashSet<TerminalCashCollection>();
            this.TerminalDataUsages = new HashSet<TerminalDataUsage>();
            this.TerminalDevices = new HashSet<TerminalDevice>();
            this.TerminalEvents = new HashSet<TerminalEvent>();
            this.TerminalHeartbeats = new HashSet<TerminalHeartbeat>();
            this.TerminalIMEIs = new HashSet<TerminalIMEI>();
            this.TerminalMACAddresses = new HashSet<TerminalMACAddress>();
            this.TransactionLogs = new HashSet<TransactionLog>();
            this.TransactionVideos = new HashSet<TransactionVideo>();
            this.VideoCalls = new HashSet<VideoCall>();
        }
    
        public int TerminalID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int TerminalTypeID { get; set; }
        public int InstitutionID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public Nullable<int> TerminalGroupID { get; set; }
        public string TerminalNumber { get; set; }
        public string AppVersion { get; set; }
        public Nullable<bool> IsInService { get; set; }
        public string Mode { get; set; }
        public Nullable<bool> IsHealthOk { get; set; }
        public Nullable<bool> IsSuppliesOk { get; set; }
        public Nullable<bool> IsCounterFull { get; set; }
        public string SIMCounter { get; set; }
        public string CashCounter { get; set; }
        public string RecyclerCounter { get; set; }
        public Nullable<System.DateTime> LastHeartbeatDateTime { get; set; }
        public string LatLong { get; set; }
        public Nullable<bool> IsRestartCommand { get; set; }
        public string Address { get; set; }
        public Nullable<int> RolloutID { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public string IP { get; set; }
        public string Contact { get; set; }
        public Nullable<int> CashCapacity { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string City { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<System.DateTime> LastTransactionDateTime { get; set; }
        public Nullable<int> LastTransactionStatus { get; set; }
        public Nullable<int> CashTotalCount { get; set; }
        public Nullable<System.DateTime> LastRemarkDateTime { get; set; }
        public string CashTotalSum { get; set; }
        public string TerminalAppVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertNotification> AlertNotifications { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisputedTransaction> DisputedTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForceRestart> ForceRestarts { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual InstitutionStore InstitutionStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KioskLog> KioskLogs { get; set; }
        public virtual Region Region { get; set; }
        public virtual Rollout Rollout { get; set; }
        public virtual TerminalGroup TerminalGroup { get; set; }
        public virtual TerminalType TerminalType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalAppVersion> TerminalAppVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalCashCollection> TerminalCashCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalDataUsage> TerminalDataUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalDevice> TerminalDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalEvent> TerminalEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalHeartbeat> TerminalHeartbeats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalIMEI> TerminalIMEIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalMACAddress> TerminalMACAddresses { get; set; }
        public virtual TerminalPowerTool TerminalPowerTool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionVideo> TransactionVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCall> VideoCalls { get; set; }
    }
}
