//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalAppVersion
    {
        public int AppVersionID { get; set; }
        public int TerminalID { get; set; }
        public string AppType { get; set; }
        public string AppVersion { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
