//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalCashCollection
    {
        public int TerminalCashCollectionID { get; set; }
        public int TerminalID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string StaffID { get; set; }
        public Nullable<int> CashTotal { get; set; }
        public string CashBreakup { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsCollected { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
