//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerminalDevice()
        {
            this.DeviceReInits = new HashSet<DeviceReInit>();
            this.TerminalDeviceEvents = new HashSet<TerminalDeviceEvent>();
        }
    
        public int TerminalDeviceID { get; set; }
        public int TerminalID { get; set; }
        public int DeviceID { get; set; }
        public string Heath { get; set; }
        public string Supply { get; set; }
        public Nullable<System.DateTime> LastIncident { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceReInit> DeviceReInits { get; set; }
        public virtual Terminal Terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalDeviceEvent> TerminalDeviceEvents { get; set; }
    }
}
