//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalHeartbeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerminalHeartbeat()
        {
            this.TerminalHeartbeatDetails = new HashSet<TerminalHeartbeatDetail>();
        }
    
        public int TerminalHeartbeatID { get; set; }
        public int TerminalID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string LatLong { get; set; }
    
        public virtual Terminal Terminal { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalHeartbeatDetail> TerminalHeartbeatDetails { get; set; }
    }
}
