//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalHeartbeatDetail
    {
        public int TerminalHeartbeatDetailID { get; set; }
        public string DetailKey { get; set; }
        public string DetailValue { get; set; }
        public int TerminalHeartbeatID { get; set; }
    
        public virtual TerminalHeartbeat TerminalHeartbeat { get; set; }
    }
}
