//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionVideo
    {
        public int TransactionVideoID { get; set; }
        public string STAN { get; set; }
        public int TerminalID { get; set; }
        public string Filename { get; set; }
        public System.DateTime RecordingDate { get; set; }
        public bool IsAvalailable { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
