//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionField()
        {
            this.InstitutionParameterValues = new HashSet<InstitutionParameterValue>();
            this.TemplateTransactionFields = new HashSet<TemplateTransactionField>();
            this.TransactionAttributes = new HashSet<TransactionAttribute>();
            this.TransactionFieldOptions = new HashSet<TransactionFieldOption>();
        }
    
        public int TransactionFieldID { get; set; }
        public string Name { get; set; }
        public string FieldType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Question { get; set; }
        public string SubQuestion { get; set; }
        public string ControlLabel { get; set; }
        public string ControlType { get; set; }
        public string PlaceHolderText { get; set; }
        public bool HasMention { get; set; }
        public bool HasAttribute { get; set; }
        public bool IsSuppressed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitutionParameterValue> InstitutionParameterValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateTransactionField> TemplateTransactionFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionAttribute> TransactionAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionFieldOption> TransactionFieldOptions { get; set; }
    }
}
