//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionFieldOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionFieldOption()
        {
            this.TemplateTransactionFieldOpts = new HashSet<TemplateTransactionFieldOpt>();
        }
    
        public int TransactionFieldOptionID { get; set; }
        public string Title { get; set; }
        public int TransactionFieldID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateTransactionFieldOpt> TemplateTransactionFieldOpts { get; set; }
        public virtual TransactionField TransactionField { get; set; }
    }
}
