//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionAttribute()
        {
            this.InstitutionParameterAtts = new HashSet<InstitutionParameterAtt>();
        }
    
        public int TransactionAttributeID { get; set; }
        public string Key { get; set; }
        public string ValueSet { get; set; }
        public int TransactionFieldID { get; set; }
        public string Question { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitutionParameterAtt> InstitutionParameterAtts { get; set; }
        public virtual TransactionField TransactionField { get; set; }
    }
}
