//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionLog()
        {
            this.ChequeLogs = new HashSet<ChequeLog>();
            this.DisputedTransactions = new HashSet<DisputedTransaction>();
            this.GeneralLedgers = new HashSet<GeneralLedger>();
        }
    
        public int TransactionLogID { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> ResponseCodeCategoryID { get; set; }
        public string MessageCodeID { get; set; }
        public string ServiceID { get; set; }
        public string SourceInstitutionID { get; set; }
        public string SourceSubInstitutionID { get; set; }
        public string SourceChannelID { get; set; }
        public string SourceTransactionID { get; set; }
        public Nullable<System.DateTime> SourceDateTime { get; set; }
        public string SourceLanguage { get; set; }
        public string DeviceAppVersion { get; set; }
        public string DeviceConfigVersion { get; set; }
        public string DeviceUserID { get; set; }
        public string DeviceSessionID { get; set; }
        public string DeviceIMEI { get; set; }
        public string DeviceLongitude { get; set; }
        public string DeviceLattitude { get; set; }
        public string ServiceInstitutionID { get; set; }
        public string ServiceProductID { get; set; }
        public string ServiceRequestType { get; set; }
        public string ServiceConsumerNumber { get; set; }
        public string TransactionCurrency { get; set; }
        public Nullable<double> TransactionAmount { get; set; }
        public string TransactionSettledCurrency { get; set; }
        public Nullable<double> TransactionSettledAmount { get; set; }
        public Nullable<double> TransactionFee { get; set; }
        public Nullable<double> TransactionVAT { get; set; }
        public Nullable<double> TransactionTotalAmount { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentCurrency { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<double> PaymentExchangeRate { get; set; }
        public Nullable<double> PaymentConvertedAmount { get; set; }
        public string PaymentCardNumber { get; set; }
        public string PaymentConsumerNumber { get; set; }
        public string PaymentQRCode { get; set; }
        public string PaymentNFCTagID { get; set; }
        public string mPOSRRN { get; set; }
        public string mPOSTerminalID { get; set; }
        public string mPOSBatchID { get; set; }
        public string mPOSTraceID { get; set; }
        public string mPOSMerchantID { get; set; }
        public string mPOSApplicationID { get; set; }
        public string RequestAdditionalInfo1 { get; set; }
        public string RequestAdditionalInfo2 { get; set; }
        public string RequestAdditionalInfo3 { get; set; }
        public string RequestAdditionalInfo4 { get; set; }
        public string RequestAdditionalInfo5 { get; set; }
        public string TransferInstitutionType { get; set; }
        public string TransferCountry { get; set; }
        public string TransferInstitution { get; set; }
        public string TransferBank { get; set; }
        public string TransferAccountNumber { get; set; }
        public string TransferIBAN { get; set; }
        public string TransferAccountTitle { get; set; }
        public string TransferReason { get; set; }
        public string TransferReferenceNumber { get; set; }
        public string TransferDetails { get; set; }
        public string RetailerID { get; set; }
        public string RetailStoreID { get; set; }
        public string RetailCounterID { get; set; }
        public string RetailSaleDateTime { get; set; }
        public string RetailerReferencenumber { get; set; }
        public string RetailTotalItem { get; set; }
        public bool Timeout { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public string ResponseMessage { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public string KYCFullName { get; set; }
        public Nullable<System.DateTime> KYCDOB { get; set; }
        public string KYCPlaceOfBirth { get; set; }
        public string KYCCountryOfBirth { get; set; }
        public string KYCNationality { get; set; }
        public string KYCMobileNumber { get; set; }
        public string KYCPassportNo { get; set; }
        public Nullable<System.DateTime> KYCPassportExpiry { get; set; }
        public string KYCIDType { get; set; }
        public string KYCIDNumber { get; set; }
        public string KYCIDExpiry { get; set; }
        public string KYCHomeAddress { get; set; }
        public string KYCMotherMaidenName { get; set; }
        public Nullable<int> HostSettlementCycleID { get; set; }
        public Nullable<int> AgentSettlementCycleID { get; set; }
        public Nullable<int> AgentOfflineHistoryID { get; set; }
        public string TransactionMode { get; set; }
        public string HostRetrievalNumber { get; set; }
        public Nullable<int> AppMenuID { get; set; }
        public Nullable<int> ResponseCodeID { get; set; }
        public Nullable<int> HostResponseCodeID { get; set; }
        public Nullable<int> ProductCodeID { get; set; }
        public string DeviceMACAddress { get; set; }
        public Nullable<int> TerminalCashCollectionID { get; set; }
        public string TransactionRequest { get; set; }
        public string TransactionResponse { get; set; }
        public string NoteBreakdown { get; set; }
        public Nullable<double> TotalEarning { get; set; }
        public Nullable<double> BreakageEarned { get; set; }
    
        public virtual AgentOfflineHistory AgentOfflineHistory { get; set; }
        public virtual AgentSettlementCycle AgentSettlementCycle { get; set; }
        public virtual AppMenu AppMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChequeLog> ChequeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisputedTransaction> DisputedTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralLedger> GeneralLedgers { get; set; }
        public virtual HostResponseCode HostResponseCode { get; set; }
        public virtual HostSettlementCycle HostSettlementCycle { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual ProductCode ProductCode { get; set; }
        public virtual ResponseCode ResponseCode { get; set; }
        public virtual ResponseCodeCategory ResponseCodeCategory { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
