//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAPIStatu
    {
        public int ID { get; set; }
        public string API { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> LastAPIUpdate { get; set; }
    }
}
