//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRBeneficiaryField
    {
        public string CountryCode { get; set; }
        public string PaymentMode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Address { get; set; }
        public string DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string Nationality { get; set; }
        public string IDNumber { get; set; }
        public string IDType { get; set; }
        public string PayOutCurrency { get; set; }
        public string PayOutBranchCode { get; set; }
        public string BankName { get; set; }
        public string BankCountry { get; set; }
        public string BranchNameAndAddress { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public string PurposeCode { get; set; }
        public string PayoutCountryCode { get; set; }
        public string Customer_Relation { get; set; }
    }
}
