//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRCashNetwork
    {
        public int ID { get; set; }
        public string PayOutAgent { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string PayOutBranchCode { get; set; }
        public string PayOutCurrencyCode { get; set; }
        public string PaymentMode { get; set; }
        public string City { get; set; }
        public string CityCode { get; set; }
        public string Location { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TRCountry TRCountry { get; set; }
    }
}
