//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavorite
    {
        public int UserFavoriteID { get; set; }
        public int UserID { get; set; }
        public int ServiceMenuID { get; set; }
    
        public virtual AppMenu AppMenu { get; set; }
        public virtual User User { get; set; }
    }
}
