//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroup()
        {
            this.NotificationDeliveries = new HashSet<NotificationDelivery>();
            this.UserGroupLevels = new HashSet<UserGroupLevel>();
            this.UserSets = new HashSet<UserSet>();
        }
    
        public int UserGroupID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> PermissionGroupID { get; set; }
        public Nullable<int> TransactionGroupID { get; set; }
        public Nullable<int> AppMenuGroupID { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> WidgetGroupID { get; set; }
        public Nullable<int> FeeGroupID { get; set; }
        public Nullable<int> VATGroupID { get; set; }
        public Nullable<int> AgentSettlementGroupID { get; set; }
        public Nullable<int> PreFundingGroupID { get; set; }
        public Nullable<int> AgentLimitGroupID { get; set; }
        public Nullable<int> CommissionGroupID { get; set; }
        public Nullable<bool> IsAgentGroup { get; set; }
        public Nullable<bool> IsOfflineMode { get; set; }
        public Nullable<int> PerformanceGroupID { get; set; }
    
        public virtual AgentLimitGroup AgentLimitGroup { get; set; }
        public virtual AgentSettlementGroup AgentSettlementGroup { get; set; }
        public virtual AppMenuGroup AppMenuGroup { get; set; }
        public virtual CommissionGroup CommissionGroup { get; set; }
        public virtual FeeGroup FeeGroup { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationDelivery> NotificationDeliveries { get; set; }
        public virtual PerformanceGroup PerformanceGroup { get; set; }
        public virtual PermissionGroup PermissionGroup { get; set; }
        public virtual PreFundingGroup PreFundingGroup { get; set; }
        public virtual TransactionGroup TransactionGroup { get; set; }
        public virtual VATGroup VATGroup { get; set; }
        public virtual WidgetGroup WidgetGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroupLevel> UserGroupLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSet> UserSets { get; set; }
    }
}
