//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_Automate_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCall
    {
        public int VideoCallID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int TerminalID { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<System.DateTime> CallRecieved { get; set; }
    
        public virtual Terminal Terminal { get; set; }
        public virtual User User { get; set; }
    }
}
